# Generated by Django 2.1 on 2019-12-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20191217_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='deleted',
            new_name='done',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
    ]
