# Generated by Django 2.1 on 2019-12-27 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20191227_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='delete',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
